### ISSUE TITLE
Arduino Servo Library doesn't output the values that the servo is expecting

### ISSUE THREAD

**Issue by Nrpickle** [Nrpickle/ROSS#4]
See what the ESC is expecting, and add the optional min and max to the Arduino Servo library

https://www.arduino.cc/en/Reference/ServoAttach

See the notes on the Toughbook to see what the ESC is looking for by default, and compare this to the card

**Comment by RobJShannon** [comment]
Values in milliseconds
Neutral: 1.479
Max Forward: 1.910
Max Reverse: 1.048
Largest Braking Threshold: .15
View current values: Prog -> Basic -> Current Settings
