### ISSUE TITLE
Create "setWinchSpeed" function (or equivalent)

### ISSUE THREAD

**Issue by Nrpickle** [Nrpickle/ROSS#7]
This function will take into account "previous speed" and "desired speed" and make a change in a time that is configurable via a #define at the top of the program.

Something approaching ["S-Curve Acceleration"](http://www.ni.com/product-documentation/4824/en/) should be implemented. It would be 100% desired to use a sin() function to do this, but it might not be realistic. Really, this depends on how fast your control loop is running.

**Comment by Nrpickle** [comment]
Make sure that the "stop" position is configurable

**Comment by Nrpickle** [comment]
I would use something like this:

``` c
enum {UP, DOWN, STOP} //setWinchPower direction enum 

/*
desiredPower : 0 - 100 (percent), value does not matter when desiredDIrection is STOP
desiredDirection: reference the setWinchPower direction enum
*/
void setWinchPower(uint8_t desiredPower, uint8_t desiredDirection);  //Set the winch power
```

**Comment by Nrpickle** [comment]
The 

``` c
void sendStatus()
```

function should reference the `setWinchPower` function's "current" status, instead of other variables in the program when outputting directions for status messages

**Comment by Nrpickle** [comment]
A good backend for this could be

``` c
struct {
  uint8_t currentPower;
  uint8_t currentDirection;
} winch;
```

if you wanted to implement it as a class, then `currentPower` and `currentDirection` would be private variables that can only be accessed by the `setWinchPower()` function, to ensure that it is the only thing that sets speeds. It should also be the _only_ function that calls `ESC.write()`.

**Comment by Nrpickle** [comment]
The `ServoWriteMicroseconds()` Arduino function might be handy [[link]](https://www.arduino.cc/en/Reference/ServoWriteMicroseconds)

**Comment by Nrpickle** [comment]
Ooh.

How about this?

``` c
struct {
  uint8_t currentPower;
  uint8_t prevPower;
  uint8_t currentDir;
  uint8_t prevDir;
  uint8_t upToDate;
} winch;

static void setWinchPower(uint8_t desiredPower, uint8_t desiredDirection){
  //This function needs to be be able to be called continuously throughout the exectution of the program
  //You may want the transition time to be ~1 second and you can't go blocking your program for that entire time.

  if(desiredPower == winch.currentPower && desiredDirection == winch.currentDir){
    //set prevPower = currentPower
    return;  //We are up to date
  }

  //Scenario: we are currently at DOWN 40 and want to go to UP 80, sinusodially.

  //Scale output power to 0 to 200 (100 being stop) then you want

  uint8_t powerDifference = //Then relate this to a number that's negative if the speed needs to "decrease" on the 200 number scale

  int powerToSend  = ((sin(out of phase -pi/2) + 1)/2 * powerDifference) + winch.prevPower; //This should give you a number that ranges from 0 to 100 that sinusodially goes between the previous power, and the one you want

  winch.currentPower = powerToSend;

  //actually output the power

  //check if the're the same
  //if(winch.currentPower = desiredPower){
  //  winch.prevPower = desiredPower;
  }
}

```

**Comment by RobJShannon** [comment]
(sin(pi(t/500)-pi/2)+1)/2
